<? include("inc/conn.inc.php"); 
verifyAcess("CADCLIENTE","T");
$CLIEN_COL_PESSOA = modifyData($_POST["CLIEN_COL_PESSOA"]);
$CLIEN_QTDELINHANF = modifyData($_POST["CLIEN_QTDELINHANF"]);
$CLIEN_COL_ENDER = modifyData($_POST["CLIEN_COL_ENDER"]);
$CLIEN_COL_BAIRRO = modifyData($_POST["CLIEN_COL_BAIRRO"]);
$CLIEN_COL_CIDADE = modifyData($_POST["CLIEN_COL_CIDADE"]);
$CLIEN_COL_FONE = modifyData($_POST["CLIEN_COL_FONE"]);
$CLIEN_COL_UF = modifyData($_POST["CLIEN_COL_UF"]);
$CLIEN_COL_DIAINI = modifyData($_POST["CLIEN_COL_DIAINI"]);
$CLIEN_COL_DIAFIM = modifyData($_POST["CLIEN_COL_DIAFIM"]);
$CLIEN_COL_HRINI = modifyData($_POST["CLIEN_COL_HRINI"]);
$CLIEN_COL_HRFIM = modifyData($_POST["CLIEN_COL_HRFIM"]);
$CLIEN_COL_LOJAANT = modifyData($_POST["CLIEN_COL_LOJAANT"]);  //INCLUIDO EM 17/11/20O5
$CLIEN_COL_LOJAANT_1 = modifyData($_POST["CLIEN_COL_LOJAANT_1"]);  //INCLUIDO EM 25/01/20O6
$CLIEN_COL_LOJAANT_2 = modifyData($_POST["CLIEN_COL_LOJAANT_2"]);  //INCLUIDO EM 25/01/20O6
$CLIEN_COL_LOJAANT_3 = modifyData($_POST["CLIEN_COL_LOJAANT_3"]);  //INCLUIDO EM 25/01/20O6
$CLIEN_COL_LOJAANT_4 = modifyData($_POST["CLIEN_COL_LOJAANT_4"]);  //INCLUIDO EM 25/01/20O6
$CLIEN_OPELJ_IDO = modifyData($_POST["CLIEN_OPELJ_IDO"]);
$CLIEN_COL_LOJAPROPRIA = modifyData($_POST["CLIEN_COL_LOJAPROPRIA"]);

if ($CLIEN_COL_LOJAPROPRIA == ""){
	$CLIEN_COL_LOJAPROPRIA = 0;
}

$CLIEN_COB_BANCO 			=  modifyData($_POST["CLIEN_COB_BANCO"]); 
$CLIEN_COB_AGENCIA_CODIGO 	=  modifyData($_POST["CLIEN_COB_AGENCIA_CODIGO"]);
$CLIEN_COB_AGENCIA_NOME 	=  modifyData($_POST["CLIEN_COB_AGENCIA_NOME"]); 
$CLIEN_COB_CONTA 			=  modifyData($_POST["CLIEN_COB_CONTA"]); 
$CLIEN_COB_TITULAR 			=  modifyData($_POST["CLIEN_COB_TITULAR"]);

$CLIEN_COB2_BANCO 			=  modifyData($_POST["CLIEN_COB2_BANCO"]); 
$CLIEN_COB2_AGENCIA_CODIGO 	=  modifyData($_POST["CLIEN_COB2_AGENCIA_CODIGO"]);
$CLIEN_COB2_AGENCIA_NOME 	=  modifyData($_POST["CLIEN_COB2_AGENCIA_NOME"]); 
$CLIEN_COB2_CONTA 			=  modifyData($_POST["CLIEN_COB2_CONTA"]); 
$CLIEN_COB2_TITULAR 		=  modifyData($_POST["CLIEN_COB2_TITULAR"]);

	$Stmt = mysql_query("SELECT CLIEN_COL_PESSOA FROM rar_cliente_coleta WHERE CLIEN_COL_PESSOA = '" .$CLIEN_COL_PESSOA. "'");
	if (!mysql_fetch_assoc($Stmt)) {
		$Stmt = mysql_query("INSERT INTO rar_cliente_coleta (CLIEN_COL_PESSOA) VALUES ('" .$CLIEN_COL_PESSOA. "')");
	}
	
	//INCLUIDO EM 17/11/20O5
	if ($CLIEN_COL_LOJAANT == ""){
		$CLIEN_COL_LOJAANT = "Null";
	}
	//FIM DA INCLUSAO

        //INCLUIDO EM 26/01/2006
	if ($CLIEN_COL_LOJAANT_1 == ""){
		$CLIEN_COL_LOJAANT_1 = "Null";
	}
    
	if ($CLIEN_COL_LOJAANT_2 == ""){
		$CLIEN_COL_LOJAANT_2 = "Null";
	}
    
	if ($CLIEN_COL_LOJAANT_3 == ""){
		$CLIEN_COL_LOJAANT_3 = "Null";
	}
    
	if ($CLIEN_COL_LOJAANT_4 == ""){
		$CLIEN_COL_LOJAANT_4 = "Null";
	}
	//FIM DA INCLUSAO
	
	$Sql = "UPDATE rar_cliente_coleta SET " .
		   "CLIEN_QTDELINHANF = '" .$CLIEN_QTDELINHANF. "' ".
		   ",CLIEN_OPELJ_IDO = '" .$CLIEN_OPELJ_IDO. "' ".
		   ",CLIEN_COL_ENDER = '" .$CLIEN_COL_ENDER. "' ".
		   ",CLIEN_COL_BAIRRO = '" .$CLIEN_COL_BAIRRO. "' ".
		   ",CLIEN_COL_CIDADE = '" .$CLIEN_COL_CIDADE. "' ".
		   ",CLIEN_COL_UF = '" .$CLIEN_COL_UF. "' ".
		   ",CLIEN_COL_FONE = '" .$CLIEN_COL_FONE. "' ".
		   ",CLIEN_COL_DIAINI = '" .$CLIEN_COL_DIAINI. "' ".
		   ",CLIEN_COL_DIAFIM = '" .$CLIEN_COL_DIAFIM. "' ".
		   ",CLIEN_COL_LOJAANT = " .$CLIEN_COL_LOJAANT.  //INCLUIDO EM 17/11/20O5
		   ",CLIEN_COL_LOJAANT_1 = " .$CLIEN_COL_LOJAANT_1.  //INCLUIDO EM 25/01/2006
		   ",CLIEN_COL_LOJAANT_2 = " .$CLIEN_COL_LOJAANT_2.  //INCLUIDO EM 25/01/2006
		   ",CLIEN_COL_LOJAANT_3 = " .$CLIEN_COL_LOJAANT_3.  //INCLUIDO EM 25/01/2006
		   ",CLIEN_COL_LOJAANT_4 = " .$CLIEN_COL_LOJAANT_4.  //INCLUIDO EM 25/01/2006
		   ",CLIEN_COL_LOJAANT_4 = " .$CLIEN_COL_LOJAANT_4.  //INCLUIDO EM 25/01/2006
		   
		   ",CLIEN_COL_LOJAPROPRIA = " .$CLIEN_COL_LOJAPROPRIA.  
		   
		   
		   ",CLIEN_COB_BANCO 			= '" .$CLIEN_COB_BANCO."' ".  //INCLUIDO EM 27/07/2006
		   ",CLIEN_COB_AGENCIA_CODIGO 	= '" .$CLIEN_COB_AGENCIA_CODIGO."' ".  //INCLUIDO EM 27/07/2006
		   ",CLIEN_COB_AGENCIA_NOME 	= '" .$CLIEN_COB_AGENCIA_NOME."' ".  //INCLUIDO EM 27/07/2006
		   ",CLIEN_COB_CONTA 			= '" .$CLIEN_COB_CONTA."' ".  //INCLUIDO EM 27/07/2006
		   ",CLIEN_COB_TITULAR 			= '" .$CLIEN_COB_TITULAR."' ".  //INCLUIDO EM 27/07/2006
		   
		   ",CLIEN_COB2_BANCO 			= '" .$CLIEN_COB2_BANCO."' ".  //INCLUIDO EM 27/07/2006
		   ",CLIEN_COB2_AGENCIA_CODIGO 	= '" .$CLIEN_COB2_AGENCIA_CODIGO."' ".  //INCLUIDO EM 27/07/2006
		   ",CLIEN_COB2_AGENCIA_NOME 	= '" .$CLIEN_COB2_AGENCIA_NOME."' ".  //INCLUIDO EM 27/07/2006
		   ",CLIEN_COB2_CONTA 			= '" .$CLIEN_COB2_CONTA."' ".  //INCLUIDO EM 27/07/2006
		   ",CLIEN_COB2_TITULAR 		= '" .$CLIEN_COB2_TITULAR."' ".  //INCLUIDO EM 27/07/2006
		   
		   ",CLIEN_COL_HRINI = date_format('2005-01-01 " .$CLIEN_COL_HRINI. ":00','%d/%m/%y %H:%i:%s') ".
		   ",CLIEN_COL_HRFIM = date_format('2005-01-01 " .$CLIEN_COL_HRFIM. ":00','%d/%m/%y %H:%i:%s') WHERE CLIEN_COL_PESSOA = '" .$CLIEN_COL_PESSOA. "'";
	$Stmt = mysql_query($Sql);
	header("Location: pesq_cliente.php");	
?>